"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Produto_1 = require("./Produto");
var produto = new Produto_1.Produto(3, "Blusa", 45.65, "Roupa");
Produto_1.Produto.cadastrarProduto(produto);
Produto_1.Produto.cadastrarProduto(new Produto_1.Produto(1, "Espelho", 10.9, "casa"));
Produto_1.Produto.cadastrarProduto(new Produto_1.Produto(2, "Toalha", 59.00, "Banho"));
Produto_1.Produto.atualizarProduto(3, "Espelho", 10.9, "Categoria");
Produto_1.Produto.removerProduto(1);
Produto_1.Produto.listarProdutos();
